spring:
  datasource:
    url: jdbc:mysql://mydb.clz02g0uqvzz.ap-northeast-2.rds.amazonaws.com/joo2study
    username: root
    password: umcteame
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
logging:
  level:
    org.springframework.data: DEBUG