spring:
  datasource:
    url: jdbc:mysql://localhost/joo2study
    username: root
    password: 20190976sswu
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
logging:
  level:
    org.springframework.data: DEBUG