spring:
  datasource:
    url: jdbc:mysql://localhost/joo2study
    username: root
    password: 20190976sswu
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 300MB

server:
  port: 8080
logging:
  level:
    org.springframework.data: DEBUG