spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?createDatabaseIfNotExist=true
    username: root
    password: 00000819
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080
logging:
  level:
    org.springframework.data: DEBUG

chatgpt:
  key: ${GPT_SECRET}